# Generated by Django 4.2.27 on 2026-01-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(choices=[(1, '1º Ano'), (2, '2º Ano'), (3, '3º Ano')])),
                ('codigo', models.CharField(help_text='Ex. A, B, C ...', max_length=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ano', 'codigo'],
                'unique_together': {('ano', 'codigo')},
            },
        ),
    ]
